---
- name: Set Hadoop Env
  become_user: hadoop
  shell: source /etc/profile.d/hadoop_env.sh
  
- name: Set Hive Env
  become_user: hadoop
  shell: source /etc/profile.d/hive_env.sh
  
- name: Init hdfs path
  become_user: hadoop
  shell: "/opt/hadoop/hadoop-2.7.2/bin/hdfs dfs -ls /"
#   shell: su {{ user }} -c "hdfs dfs -mkdir -p {{ item }}"
#   with_items:
#     - "{{ hive_hdfs_path }}"

# - name: Change Authority
#   shell: su {{ user }} -c "hdfs dfs -chmod -R 777 {{ item }}"
#   with_items:
#     - "{{ hive_hdfs_path }}"

# - name: Init Hive
#   shell: su {{ user }} -c "schematool -initSchema -dbType {{ db_type }}"
