- hosts: hive
  become: True 
  remote_user: root
  vars_files:
   - vars/user.yml
   - vars/var_java.yml
   - vars/var_hadoop.yml
   - vars/var_master.yml
   - vars/var_hive.yml
  vars:
     open_firewall: false
     install_hive: false
     config_hive: false
     init_hive: true
  roles:
    - hive
