- hosts: master 
  become: True
  remote_user: root
  vars_files:
   - vars/user.yml
   - vars/var_java.yml
   - vars/var_hadoop.yml
   - vars/var_master.yml
  vars:
     add_user: false
     generate_key: false
     open_firewall: false
     disable_firewall: false
     install_hadoop: false
     config_hadoop: true
  roles:
    - user
    - fetch_public_key
    - authorized
    - java
    - hadoop
