# install spark in master node and generate public key by master
- hosts: master
  become: True
  remote_user: root
  vars_files:
   - vars/var_java.yml
   - vars/var_hadoop.yml
   - vars/var_spark.yml
   - vars/var_master.yml
  vars:
     user: "spark"
     group: "spark"
     add_user: true
     generate_key: true
     install_spark: true
  roles:
    - user
    - fetch_public_key
    - authorized
    - spark


