#install worker nodes and fetch public key by master
- hosts: workers
  become: True
  remote_user: root
  vars_files:
   - vars/var_java.yml
   - vars/var_hadoop.yml
   - vars/var_spark.yml
   - vars/var_master.yml
  vars:
     user: "spark"
     group: "spark"
     add_user: false
     generate_key: false
     install_spark: false
  roles:
    - user
    - authorized
    - spark
