# do they need keys ? do they have to be installed in all nodes? or just python and java?

- hosts: master # and workers
  remote_user: root
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
   - vars/var_master.yml
  vars:
     add_user: true
     generate_key: true
     open_firewall: false
     disable_firewall: false
     install_hadoop: true
     config_hadoop: true
  roles:
    - user
    - fetch_public_key
    - authorized
    - spark
