# do they need keys ? do they have to be installed in all nodes? or just python and java?

- hosts: master # and workers
  remote_user: root
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
   - vars/var_master.yml
  vars:
     add_user: false
     generate_key: false
     open_firewall: false
     disable_firewall: false
     install_hadoop: false
     config_hadoop: false
  roles:
    - spark
