---
- name: Create spark paths
  file: 
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    state: directory
    mode: 0755
  become: true  
  with_items:
    - "{{ spark_create_path }}" # work & logs
    
- name: Copy spark-defaults.conf
  template: src=spark-defaults.conf.j2 dest={{ spark_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Set slaves
  template: src="slaves" dest="{{ spark_config_path }}/slaves.j2" mode=644 owner={{ user }} group = {{ group }}

- name: Set spark-env.sh
  template: src="spark-env.sh" dest="{{ spark_config_path }}/spark-env.sh.j2" mode=644 owner={{ user }} group = {{ group }}

- name: Copy spark profile script
  template: src=spark-profile.sh.j2 dest=/etc/profile.d/ mode=755 owner={{ user }} group = {{ group }}

- name: Set spark profile
  shell: source /etc/profile.d/spark-profile.sh

