---
  
- name: Copy spark-defaults.conf
  template: src=spark-defaults.conf.j2 dest={{ spark_config_path }}/spark-defaults.conf mode=644 owner={{ user }} group = {{ group }}

- name: Set slaves
  template: src="slaves.j2" dest="{{ spark_config_path }}/slaves" mode=644 owner={{ user }} group = {{ group }}

- name: Set spark-env.sh
  template: src="spark-env.sh.j2" dest="{{ spark_config_path }}/spark-env.sh" mode=644 owner={{ user }} group = {{ group }}

- name: Copy spark profile script
  template: src=spark-profile.sh.j2 dest=/etc/profile.d/spark-profile.sh mode=755 owner={{ user }} group = {{ group }}

- name: Set spark profile
  shell: source /etc/profile.d/spark-profile.sh

